apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  labels:
    grafana_datasource: "1"
    namespace: grafana
  {{- include "grafana.labels" . | nindent 4 }}
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
    - name: Postgres
      type: postgres
      url:  postgre-db-svc.hub.svc.cluster.local:5432
      user: hub
      secureJsonData:
        password: 'c67'
      jsonData:
        database: hub
        sslmode: 'disable' # disable/require/verify-ca/verify-full
        maxOpenConns: 100 # Grafana v5.4+
        maxIdleConns: 100 # Grafana v5.4+
        maxIdleConnsAuto: true # Grafana v9.5.1+
        connMaxLifetime: 14400 # Grafana v5.4+
        postgresVersion: 903 # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
        timescaledb: false    
  grafana.ini: {{ .Values.config.grafanaIni | quote }}