---
# Source: kalypso-observability-hub/templates/api-server.yaml
apiVersion: v1
kind: Secret
metadata:
  name: api-server-secret
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/created-by: kalypso-observability-hub
    app.kubernetes.io/part-of: kalypso-observability-hub
    control-plane: api-server
type: Opaque
data:
  POSTGRES_USER: Y3JlYXRvcg==
  POSTGRES_PASSWORD: YzY3
---
# Source: kalypso-observability-hub/templates/api-server.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-server-config
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/created-by: kalypso-observability-hub
    app.kubernetes.io/part-of: kalypso-observability-hub
    control-plane: api-server
data:
  POSTGRES_HOST: localhost
  POSTGRES_PORT: "5432"
  POSTGRES_DBNAME: hub
  POSTGRES_SSL_MODE: disable
---
# Source: kalypso-observability-hub/templates/api-server.yaml
apiVersion: v1
kind: Service
metadata:
  name: kalypso-observability-hub-api-server
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/created-by: kalypso-observability-hub
    app.kubernetes.io/part-of: kalypso-observability-hub
    control-plane: api-server
spec:
  ports:
  - name: grpc-port
    port: 50051
    protocol: TCP
    targetPort: grpc-port
  selector:
    control-plane: api-server
  type: ClusterIP
---
# Source: kalypso-observability-hub/templates/api-server.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kalypso-observability-hub-api-server
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/created-by: kalypso-observability-hub
    app.kubernetes.io/part-of: kalypso-observability-hub
    control-plane: api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: api-server
  template:
    metadata:
      labels:
        control-plane: api-server
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
                - ppc64le
                - s390x
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
      containers:
      - name: api-server      
        command:
        - /server
        env:
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_HOST
              name: api-server-config
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_PORT
              name: api-server-config
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: POSTGRES_USER
              name: api-server-secret
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_PASSWORD
              name: api-server-secret
        - name: POSTGRES_DBNAME
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_DBNAME
              name: api-server-config
        - name: POSTGRES_SSL_MODE
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_SSL_MODE
              name: api-server-config
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: cluster.local
        image: ghcr.io/microsoft/kalypso-observability-hub-grpc-api-server:0.0.1-3
        readinessProbe:
          exec:
            command: ["/grpc_health_probe", "-addr=:50051"]
          initialDelaySeconds: 5
        livenessProbe:
          exec:
            command: ["/grpc_health_probe", "-addr=:50051"]
          initialDelaySeconds: 10
        name: manager
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        ports:
        - name: grpc-port
          containerPort: 50051  
      terminationGracePeriodSeconds: 10
