apiVersion: v1
kind: Secret
metadata:
  name: postgre-db-secret
  labels:
  {{- include "postgres.labels" . | nindent 4 }}
stringData:
  password: {{ required "secret.password is required" .Values.secret.password | quote
    }}
  username: {{ required "secret.username is required" .Values.secret.username | quote
    }}