apiServer:
  replicas: 0
  image:
    repository: ghcr.io/microsoft/kalypso-observability-hub-grpc-api-server
    tag: latest
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi
  postgresHost: postgre-db-svc
  postgresPort: 5432
  postgresUser: creator
  postgresPassword: c67
  postgresDbName: hub
  postgresSslmode: disable
  service:
    type: ClusterIP
    grpcPort: 50051