---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - hub.kalypso.io
  resources:
  - azureresourcegraphs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hub.kalypso.io
  resources:
  - azureresourcegraphs/finalizers
  verbs:
  - update
- apiGroups:
  - hub.kalypso.io
  resources:
  - azureresourcegraphs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - hub.kalypso.io
  resources:
  - deploymentdescriptors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hub.kalypso.io
  resources:
  - deploymentdescriptors/finalizers
  verbs:
  - update
- apiGroups:
  - hub.kalypso.io
  resources:
  - deploymentdescriptors/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - hub.kalypso.io
  resources:
  - reconcilers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hub.kalypso.io
  resources:
  - reconcilers/finalizers
  verbs:
  - update
- apiGroups:
  - hub.kalypso.io
  resources:
  - reconcilers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kustomize.toolkit.fluxcd.io
  resources:
  - kustomizations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
