apiVersion: hub.kalypso.io/v1alpha1
kind: AzureResourceGraph
metadata:
  labels:
    app.kubernetes.io/name: azureresourcegraph
    app.kubernetes.io/instance: azureresourcegraph-sample
    app.kubernetes.io/part-of: kalypso-observability-hub
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kalypso-observability-hub
  name: azureresourcegraph-sample
spec:
  subscription: 7be1b9e7-57ca-47ff-b5ab-82e7ccb8c611
  interval: 10s
