apiVersion: source.toolkit.fluxcd.io/v1beta2
kubectl apply -f - <<EOF
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: deployment-descriptors-prod
  namespace: flux-system
spec:
  interval: 30s
  url: https://github.com/kaizentm/kalypso-gitops
  ref:
    branch: prod
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: deployment-descriptors-prod
  namespace: flux-system
spec:
  interval: 30s
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: deployment-descriptors-prod
  path: ./small/samples
  prune: true
EOF