apiVersion: v1
kind: Service
metadata:
  name: postgre-db-svc
  labels:
  {{- include "postgres.labels" . | nindent 4 }}
spec:
  type: {{ .Values.svc.type }}
  selector:
    run: postgre-db
  ports:
	{{- .Values.svc.ports | toYaml | nindent 2 -}}