config:
  grafanaIni: |-
    [auth]
      disable_login_form = true
      [auth.anonymous]
      enabled = true
      org_role = Editor
grafana:
  image:
    repository: grafana/grafana
    tag: 9.1.0
  resources:
    requests:
      # cpu: 250m
      memory: 750Mi
  grafanaScDashboard:
    image:
      repository: quay.io/kiwigrid/k8s-sidecar
      tag: 1.19.2
  port: 3000    
grafanaSvc:
  port: 3000
  type: ClusterIP
pvc:
  storageRequest: 1Gi
kubernetesClusterDomain: cluster.local
